### ISSUE TITLE
Add a logo design 

### ISSUE THREAD

**Issue by manjeetdhayal** [Webwiznitr/Hacktoberfest-Sunflower#10]
You may either create it on your own or get a logo from the internet which has a creative license.

logo design must be relevant with the topic that is portfolio website. 

Before sending the PR reply over here with logo if approved send the PR

**Comment by Neeraj2002** [comment]
I would like to do that!

**Comment by manjeetdhayal** [comment]
@Neeraj2002 I have assigned it to you. Go for it

**Comment by Neeraj2002** [comment]
Is this logo fine??
[https://res.cloudinary.com/dnnaacqq0/image/upload/v1633160344/YOUR_PORTFOLIO_free-file_bi0omi.png](url)

**Comment by manjeetdhayal** [comment]
> Is this logo fine?? [https://res.cloudinary.com/dnnaacqq0/image/upload/v1633160344/YOUR_PORTFOLIO_free-file_bi0omi.png](url)

looks good. Send the PR
