### ISSUE TITLE
Initilise the repository with Gatsby

### ISSUE THREAD

**Issue by manjeetdhayal** [Webwiznitr/Hacktoberfest-Sunflower#3]

**Comment by a-sambhab** [comment]
Hey @manjeetdhayal i want to work on this please assign it to me

**Comment by manjeetdhayal** [comment]
Hey @a-sambhab now this issue is all yours. Go for it!

**Comment by a-sambhab** [comment]
@manjeetdhayal please check pr #6 for this issue
