### ISSUE TITLE
Add portfolio design link 

### ISSUE THREAD

**Issue by manjeetdhayal** [Webwiznitr/Hacktoberfest-Sunflower#4]
## Description
- Add complete design of the portfolio website  
- Anything including figma/canva will work

**Comment by Neeraj2002** [comment]
I would like to make the design for the project!

**Comment by manjeetdhayal** [comment]
@Neeraj2002 I have assigned it to you. Go for it!

**Comment by Neeraj2002** [comment]
Heyy, I have made a base design!
I am linking the design in the assets folder under the folder name design 
I hope you like it!

More templates will be added soon!
